// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateAndSave(arg1) {
  return window['go']['main']['App']['CalculateAndSave'](arg1);
}

export function CalculatePosition(arg1) {
  return window['go']['main']['App']['CalculatePosition'](arg1);
}

export function DeleteInstrument(arg1) {
  return window['go']['main']['App']['DeleteInstrument'](arg1);
}

export function GetRecentCalculations(arg1) {
  return window['go']['main']['App']['GetRecentCalculations'](arg1);
}

export function ListInstruments(arg1) {
  return window['go']['main']['App']['ListInstruments'](arg1);
}

export function ListMarkets() {
  return window['go']['main']['App']['ListMarkets']();
}

export function UpsertInstrument(arg1) {
  return window['go']['main']['App']['UpsertInstrument'](arg1);
}
