// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CalculateAndSave(arg1:main.PositionRequest):Promise<main.PositionResult>;

export function CalculatePosition(arg1:main.PositionRequest):Promise<main.PositionResult>;

export function DeleteInstrument(arg1:string):Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetRecentCalculations(arg1:number):Promise<Array<main.CalculationRecord>>;

export function ListInstruments(arg1:string):Promise<Array<main.Instrument>>;

export function ListMarkets():Promise<Array<main.Market>>;

export function UpsertInstrument(arg1:main.InstrumentUpsertRequest):Promise<main.Instrument>;
